import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";
import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = process.argv[2] === "production";
const analyze = process.env.ANALYZE === "true";

// 目标插件目录
const targetPluginDir = "/Users/eric/ob/obsidian/.obsidian/plugins/chatgpt-md";

// 自定义插件：在构建后复制文件
const copyPlugin = {
  name: 'copy-files',
  setup(build) {
    build.onEnd(() => {
      // 确保 dist 目录存在
      if (!fs.existsSync("dist")) {
        fs.mkdirSync("dist", { recursive: true });
      }

      // 复制 manifest.json 到 dist/
      fs.copyFileSync("manifest.json", "dist/manifest.json");
      console.log("📋 已复制 manifest.json → dist/");

      // 在 CI 环境中跳过本地复制操作
      if (process.env.CI) {
        console.log("🔄 CI 环境检测到，跳过本地插件目录复制");
        return;
      }

      // 确保目标目录存在
      if (!fs.existsSync(targetPluginDir)) {
        console.log(`⚠️  目标目录不存在: ${targetPluginDir}`);
        return;
      }

      // 复制 dist/ 里的文件到插件目录（仅本地）
      const files = fs.readdirSync("dist");
      for (const file of files) {
        const srcPath = path.join("dist", file);
        const destPath = path.join(targetPluginDir, file);
        if (fs.statSync(srcPath).isFile()) {
          fs.copyFileSync(srcPath, destPath);
          console.log(`📋 已复制: dist/${file} → ${targetPluginDir}`);
        }
      }
    });
  },
};

const context = await esbuild.context({
  banner: {
    js: banner,
  },
  entryPoints: ["src/main.ts"],
  bundle: true,
  external: [
    "obsidian",
    "electron",
    "@codemirror/autocomplete",
    "@codemirror/collab",
    "@codemirror/commands",
    "@codemirror/language",
    "@codemirror/lint",
    "@codemirror/search",
    "@codemirror/state",
    "@codemirror/view",
    "@lezer/common",
    "@lezer/highlight",
    "@lezer/lr",
    ...builtins,
  ],
  format: "cjs",
  target: "es2018",
  logLevel: "info",
  sourcemap: prod ? false : "inline",

  // Enhanced tree shaking and optimization options
  treeShaking: true,
  minify: prod,

  // Production-only optimizations
  ...(prod && {
    // More aggressive minification
    minifyWhitespace: true,
    minifyIdentifiers: true,
    minifySyntax: true,

    // Advanced optimization flags
    legalComments: "none", // Remove all comments to reduce size
    keepNames: false, // Allow name mangling for smaller bundles

    // Dead code elimination
    drop: ["console", "debugger"], // Remove console.log and debugger statements

    // Pure annotations for better tree shaking
    pure: ["console.log", "console.info", "console.warn", "console.debug", "console.trace"],

    // Platform-specific optimizations
    platform: "node",

    // Bundle analysis
    metafile: analyze,
  }),

  outfile: "dist/main.js",
  plugins: [copyPlugin],
});

if (prod) {
  const result = await context.rebuild();

  // Optional: Log bundle analysis info in production
  if (result.metafile) {
    console.log("📦 Bundle analysis:");
    console.log(`📏 Output size: ${(result.metafile.outputs["dist/main.js"]?.bytes || 0 / 1024).toFixed(2)} KB`);

    // Show largest dependencies
    const inputs = Object.entries(result.metafile.inputs)
      .map(([path, data]) => ({ path, bytes: data.bytes }))
      .sort((a, b) => b.bytes - a.bytes)
      .slice(0, 10);

    console.log("🔍 Largest source files:");
    inputs.forEach(({ path, bytes }) => {
      console.log(`  ${path}: ${(bytes / 1024).toFixed(2)} KB`);
    });
  }

  process.exit(0);
} else {
  console.log("👀 监听模式启动中...");
  await context.watch();
}
